### ISSUE TITLE
BUG report

### ISSUE THREAD

**Issue by sdbds** [KohakuBlueleaf/LoCon#7]
Error running process_batch: H:\novelai-webui-aki-v2\extensions\sd-webui-additional-networks\scripts\additional_networks.py
Traceback (most recent call last):
  File "H:\novelai-webui-aki-v2\modules\scripts.py", line 395, in process_batch
    script.process_batch(p, *script_args, **kwargs)
  File "H:\novelai-webui-aki-v2\extensions\sd-webui-additional-networks\scripts\additional_networks.py", line 209, in process_batch
    network, info = lora_compvis.create_network_and_apply_compvis(du_state_dict, weight_tenc, weight_unet, text_encoder, unet)
  File "H:\novelai-webui-aki-v2\extensions\a1111-sd-webui-locon\locon_compvis.py", line 62, in create_network_and_apply_compvis
    network = LoConNetworkCompvis(
  File "H:\novelai-webui-aki-v2\extensions\a1111-sd-webui-locon\locon_compvis.py", line 289, in __init__
    self.text_encoder_loras, te_rep_modules = create_modules(
  File "H:\novelai-webui-aki-v2\extensions\a1111-sd-webui-locon\locon_compvis.py", line 266, in create_modules
    alpha = comp_state_dict[f'{lora_name}.alpha'].item()
KeyError: 'lora_te_wrapped_transformer_text_model_encoder_layers_0_self_attn_k_proj.alpha'
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

同时使用Locon模型和LoRA模型时，将LoRA模型放在add-network插件第二位时会引发Locon插件错误，同时第二个LORA模型失效。

**Comment by ClashSAN** [comment]
hello, you have submitted a similar issue to webui, despite using a different program. Please understand to submit to correct repo.

**Comment by KohakuBlueleaf** [comment]
Solved https://github.com/KohakuBlueleaf/a1111-sd-webui-locon/issues/2
